import React, { useEffect } from "react";
import * as styles from "./header.module.scss";
import { gsap } from "gsap";

const Header = () => {
  useEffect(() => {
    gsap.fromTo(
      `.${styles.backgroundImage}`, // 1. Select the background image using the class generated by SCSS
      {
        x: "-50%", // 2. Set the initial position of the image to be shifted left by 50% of its width
        filter: "blur(30px)", // 3. Add a blur effect to the image using the CSS filter property
        opacity: 0, // 4. initial opacity of the image to 0, so it's not visible
      },
      {
        x: "0%",
        filter: "blur(0px)",
        opacity: 1,
        duration: 1.5,
        delay: 0.5,
      }
    );
  }, []);
  return (
    <header className="header">
      <div className={styles.backgroundImage}></div>
    </header>
  );
};

export default Header;
